let Fields = {
	basicInfo: [
		{
			type: 'text',
			label: 'Client Name',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Client Name Cannot be Empty',
		},
		{
			type: 'text',
			label: 'Business Name',
			value: '',
			readOnly: false,
			error: true,
			required: true,
			errorMessage: 'Business Name Cannot be Empty',
		},
		{
			type: 'text',
			label: 'Website',
			value: '',
			readOnly: false,
			error: false,
			required: false,
			errorMessage: 'Website Cannot be Empty',
		},
		{
			type: 'date',
			label: 'Date',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Date Cannot be Empty',
		},
		{
			type: 'text',
			label: 'Conducted By',
			value: 'R. Sam Business Coach and Sales Growth Specialist',
			readOnly: true,
			error: false,
			required: true,
			errorMessage: '',
		},
	],
	section1: [
		{
			type: 'radio',
			label: '1. What industry are you in?',
			value: 'Other(Please Specify)',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select an option',
			options: [
				'Manufacturing',
				'Retail',
				'Service',
				'Technology',
				'Other(Please Specify)',
			],
			optionsPadding: 'pl-5',
			additionalFieldOption: 'Other(Please Specify)',
			additionalFieldValue: '',
		},
		{
			type: 'radio',
			label: '2. How many employees do you have?',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select an option',
			options: [
				'1-10',
				'11-50',
				'51-200',
				'200+',
			],
			optionsPadding: 'pl-5',
			additionalFieldOption: '',
			additionalFieldValue: '',
		},
		{
			type: 'text',
			label: '3. Where are your business locations?',
			value: '',
			readOnly: false,
			error: false,
			required: false,
			errorMessage: 'Date Cannot be Empty',
		},
		{
			type: 'radio',
			label: '4. What is your monthly and yearly revenue?',
			label2: 'Monthly Revenue:',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select an option',
			options: [
				'Less than ₹10 Lakhs',
				'₹10-25 Lakhs',
				'₹25-50 Lakhs',
				'More than ₹50 Lakhs',
			],
			optionsPadding: 'pl-10',
			optionsPadding: 'pl-10',
			additionalFieldOption: '',
			additionalFieldValue: '',
		},
		{
			type: 'radio',
			label: 'Yearly Revenue:',
			labelPadding: 'pl-5',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select an option',
			options: [
				'Less than ₹1 Crore',
				'₹1-5 Crore',
				'₹5-10 Crore',
				'More than ₹10 Crore',
			],
			optionsPadding: 'pl-10',
			additionalFieldOption: '',
			additionalFieldValue: '',
		},
		{
			type: 'text',
			label: '5. Any Special Challenges or Opportunities We Should Know About?',
			label2: 'Goals:',
			label3: 'What do you hope to achieve in the next 6-12 months for your business?',
			label3Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Where do you see your business in the next 1-3 years?',
			labelPadding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Plans',
			label2: 'What strategies or actions do you have in place to reach your business goals?',
			label2Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Challenges',
			label2: 'What’s preventing you from achieving your targets or growing your business?',
			label2Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Timeline',
			label2: 'By when do you need this issue resolved to avoid delays in your business growth?',
			label2Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Budget & Authority',
			label2: 'Who will have the final say on approving the budget for this project or solution?',
			label2Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Is there already a budget in place to achieve these goals?',
			labelPadding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Consequences',
			label2: 'What would happen if you don’t solve this problem in the next few months?',
			label2Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Implications',
			label2: 'What benefits or improvements do you expect if we solve this issue together?',
			label2Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
	],
}

export {Fields};