let Fields = {
	basicInfo: [
		{
			type: 'text',
			label: 'Client Name',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Client Name Cannot be Empty',
		},
		{
			type: 'text',
			label: 'Business Name',
			value: '',
			readOnly: false,
			error: true,
			required: true,
			errorMessage: 'Business Name Cannot be Empty',
		},
		{
			type: 'text',
			label: 'Website',
			value: '',
			readOnly: false,
			error: false,
			required: false,
			errorMessage: 'Website Cannot be Empty',
		},
		{
			type: 'date',
			label: 'Date',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Date Cannot be Empty',
		},
		{
			type: 'text',
			label: 'Conducted By',
			value: 'R. Sam Business Coach and Sales Growth Specialist',
			readOnly: true,
			error: false,
			required: true,
			errorMessage: '',
		},
	],
	section1: [
		{
			type: 'radio',
			label: '1. What industry are you in?',
			value: 'Other(Please Specify)',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select an option',
			options: [
				'Manufacturing',
				'Retail',
				'Service',
				'Technology',
				'Other(Please Specify)',
			],
			optionsPadding: 'pl-5',
			additionalFieldOption: 'Other(Please Specify)',
			additionalFieldValue: '',
		},
		{
			type: 'radio',
			label: '2. How many employees do you have?',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select an option',
			options: [
				'1-10',
				'11-50',
				'51-200',
				'200+',
			],
			optionsPadding: 'pl-5',
			additionalFieldOption: '',
			additionalFieldValue: '',
		},
		{
			type: 'text',
			label: '3. Where are your business locations?',
			value: '',
			readOnly: false,
			error: false,
			required: false,
			errorMessage: 'Date Cannot be Empty',
		},
		{
			type: 'radio',
			label: '4. What is your monthly and yearly revenue?',
			label2: 'Monthly Revenue:',
			label2Padding: 'pl-5',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select an option',
			options: [
				'Less than ₹10 Lakhs',
				'₹10-25 Lakhs',
				'₹25-50 Lakhs',
				'More than ₹50 Lakhs',
			],
			optionsPadding: 'pl-10',
			optionsPadding: 'pl-10',
			additionalFieldOption: '',
			additionalFieldValue: '',
		},
		{
			type: 'radio',
			label: 'Yearly Revenue:',
			labelPadding: 'pl-5',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select an option',
			options: [
				'Less than ₹1 Crore',
				'₹1-5 Crore',
				'₹5-10 Crore',
				'More than ₹10 Crore',
			],
			optionsPadding: 'pl-10',
			additionalFieldOption: '',
			additionalFieldValue: '',
		},
		{
			type: 'text',
			label: '5. Any Special Challenges or Opportunities We Should Know About?',
			label2: 'Goals:',
			label3: 'What do you hope to achieve in the next 6-12 months for your business?',
			label3Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Where do you see your business in the next 1-3 years?',
			labelPadding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Plans:',
			label2: 'What strategies or actions do you have in place to reach your business goals?',
			label2Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Challenges:',
			label2: 'What’s preventing you from achieving your targets or growing your business?',
			label2Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Timeline:',
			label2: 'By when do you need this issue resolved to avoid delays in your business growth?',
			label2Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Budget & Authority:',
			label2: 'Who will have the final say on approving the budget for this project or solution?',
			label2Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Is there already a budget in place to achieve these goals?',
			labelPadding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Consequences:',
			label2: 'What would happen if you don’t solve this problem in the next few months?',
			label2Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'Implications:',
			label2: 'What benefits or improvements do you expect if we solve this issue together?',
			label2Padding: 'pl-5',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
	],
	section2: [
		{
			type: 'checkbox',
			label: 'A. Marketing and Sales Tools',
			label2: '1. Which of these marketing tools do you use? (Check all that apply)',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Website',
				'Social media (e.g., Facebook, Instagram)',
				'Google Analytics',
				'Email Marketing (e.g., Mailchimp)',
				'None',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'checkbox',
			label: '2. How would you rate your marketing plan?',
			labelPadding: '22px',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Very Good',
				'Needs Improvement',
				'We don’t have one',
			],
			optionsPadding: '30px',
		},
		{
			type: 'checkbox',
			label: '3. What sales tools do you use? (Check all that apply)',
			labelPadding: '22px',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'CRM System: [Specify]',
				'Client Presentations',
				'Product or Service Catalogs',
				'FAQ (Frequently Asked Questions) Section',
				'None',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label: '4. How good is your sales team at closing deals?',
			labelPadding: 'pl-5',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select an option',
			options: [
				'Excellent',
				'Good',
				'Average',
				'Poor',
			],
			optionsPadding: 'pl-10',
			additionalFieldOption: '',
			additionalFieldValue: '',
		},
		{
			type: 'checkbox',
			label: 'B. Leadership and Training',
			label2: '1. Do you have a second line of leadership? (Check all that apply)',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Chief Operating Officer (COO)',
				'Vice President (VP)',
				'Department Heads',
				'No/Not Established',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label: '2. How ready is your leadership team to take on more work?',
			labelPadding: 'pl-5',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select an option',
			options: [
				'Very Ready',
				'Somewhat Ready',
				'Needs Training',
				'Not Ready',
			],
			optionsPadding: 'pl-10',
			additionalFieldOption: '',
			additionalFieldValue: '',
		},
		{
			type: 'radio',
			label: '3. Do you offer regular training for your team?',
			labelPadding: 'pl-5',
			value: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select an option',
			options: [
				'Yes, often',
				'Yes, but could be better',
				'No, we don’t have training programs',
			],
			optionsPadding: 'pl-10',
			additionalFieldOption: '',
			additionalFieldValue: '',
		},
		{
			type: 'checkbox',
			label: '4. What training tools do you use? (Check all that apply)',
			labelPadding: '22px',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Online Learning Platforms',
				'Workshops/Webinars',
				'None',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label: 'C. HR Processes',
			label2: '1. How effective is your hiring process?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Very Effective',
				'Somewhat Effective',
				'Needs Improvement',
				'Not Effective',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label2: '2. How would you rate your new employee onboarding process?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Excellent',
				'Good',
				'Average',
				'Poor',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'checkbox',
			label: '3. What are your employee retention strategies? (Check all that apply)',
			labelPadding: '22px',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Competitive Salaries',
				'Career Growth Opportunities',
				'Work-Life Balance Programs',
				'None',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label2: '4. How engaged are your employees with the company’s vision?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Highly Engaged',
				'Moderately Engaged',
				'Slightly Engaged',
				'Not Engaged',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label: 'D. Key Business Numbers(Strategic SWOT Analysis)',
			label2: 'Strengths: (What’s Working Well in Your Business?)',
			label2Padding: 'pl-5',
			label3: '1. Customer Base:',
			label3Padding: 'pl-10',
			label4: 'Do you have loyal, returning customers?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
		},
		{
			type: 'text',
			label: 'What’s your best-selling product or service?',
			labelPadding: 'pl-[50px]',
			fieldPadding: '50px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'radio',
			label: '2. Revenue Drivers:',
			labelPadding: 'pl-10',
			label2: 'Are you happy with your current sales and revenue?',
			label2Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
		},
		{
			type: 'text',
			label: 'What is helping you grow your revenue the most?',
			labelPadding: 'pl-[50px]',
			fieldPadding: '50px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'radio',
			label: '3. Team Capabilities:',
			labelPadding: 'pl-10',
			label2: 'Is your team performing well and aligned with your business goals?',
			label2Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label: '4. Owner’s Role:',
			labelPadding: 'pl-10',
			label2: 'Can you delegate tasks easily and focus on strategic growth?',
			label2Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label2: 'Weaknesses (What Are Your Main Business Challenges?)',
			label2Padding: 'pl-5',
			label3: '1. Customer Base:',
			label3Padding: 'pl-10',
			label4: 'Do you find it hard to attract new customers?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
		},
		{
			type: 'radio',
			label4: 'Is marketing working well for you?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label3: '2. Revenue & Profit:',
			label3Padding: 'pl-10',
			label4: 'Are profit margins lower than you would like?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
		},
		{
			type: 'radio',
			label4: 'Are there cash flow or sales fluctuations?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label3: '3. Team Performance:',
			label3Padding: 'pl-10',
			label4: 'Is your team lacking certain skills or motivation?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label3: '4. Owner Dependency:',
			label3Padding: 'pl-10',
			label4: 'Do you feel like your business depends too much on you?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label2: 'Opportunities (Where Can You Grow or Improve?)',
			label2Padding: 'pl-5',
			label3: '1. New Customers & Markets:',
			label3Padding: 'pl-10',
			label4: 'Could you reach new customers or explore different markets?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label4: 'Are there untapped opportunities in your industry?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label3: '2. Revenue & Profit:',
			label3Padding: 'pl-10',
			label4: 'Could you raise prices or offer new products to grow revenue?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label3: '3. Team Development:',
			label3Padding: 'pl-10',
			label4: 'Would training or hiring more help improve your business?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label3: '4. Owner’s Role:',
			label3Padding: 'pl-10',
			label4: 'Can you reduce your involvement by putting systems in place?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label2: 'Threats (What Risks Could Affect Your Business?)',
			label2Padding: 'pl-5',
			label3: '1. Competition:',
			label3Padding: 'pl-10',
			label4: 'Are competitors taking away your customers?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label3: '2. Revenue Fluctuations:',
			label3Padding: 'pl-10',
			label4: 'Are there external factors (like the economy) that could hurt your sales?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label3: '3. Team Challenges:',
			label3Padding: 'pl-10',
			label4: 'Are you worried about losing key employees?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label3: '4. Owner Dependency:',
			label3Padding: 'pl-10',
			label4: 'Could the business suffer if you’re unavailable for a period of time?',
			label4Padding: 'pl-[50px]',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'No',
			],
			optionsPadding: 'pl-[50px]',
			showAdditionalField: true,
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'text',
			label: 'Next Steps',
			label2: 'Based on your answers, let’s focus on 1-2 areas where you can make the biggest improvements:',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please fill out this field',
			options: [
				'Yes',
				'No',
			],
			fieldPadding: '20px',
		},
	],
	section3: [
		{
			type: 'checkbox',
			label: 'A. Unique Selling Proposition (USP)',
			label2: '1. What makes your product or service unique?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Highest Quality',
				'Lowest Price',
				'Best Customer Service',
				'Most Innovative',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'checkbox',
			label2: '2. What makes your product or service better than competitors? (Check all that apply)',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Unique Features or Technology',
				'Superior Design or Performance',
				'Excellent Customer Support',
				'Strong Brand Reputation',
				'Customization Options',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label2: '3. How well is your USP communicated to your market?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Very Well',
				'Somewhat Well',
				'Needs Improvement',
				'Not Communicated',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label2: '4. Do you have a clear brand message that shows your USP?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes',
				'Yes, but it could be clearer',
				'No',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label: 'B. Competitive Strength',
			label2: '1. How do your products or services compare to competitors in quality?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Better Quality',
				'Similar Quality',
				'Lower Quality',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label2: '2. How do your prices compare to competitors?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Lower Price',
				'Similar Price',
				'Higher Price',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label2: '3. How do you compare in customer satisfaction?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Higher Satisfaction',
				'Similar Satisfaction',
				'Lower Satisfaction',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'checkbox',
			label2: '4. What gives you a competitive advantage? (Check all that apply)',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Strong Brand Loyalty',
				'Efficient Operations',
				'Exclusive Products/Services',
				'Large Distribution Network',
				'Innovation and R&D',
				'Skilled Workforce',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'checkbox',
			label2: '5. What challenges do you face in staying competitive?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Price Competition',
				'Fast Technology Changes',
				'Market Saturation',
				'Supply Chain Issues',
				'Keeping Customers',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
	],
	section4: [
		{
			type: 'radio',
			label: 'A. Business Goals',
			label2: '1. What is your target increase in customers?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'5%',
				'10%',
				'20%',
				'Other: [Specify]',
			],
			optionsPadding: 'pl-10',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label2: '2. What is your target revenue growth?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'10%',
				'20%',
				'30%',
				'Other: [Specify]',
			],
			optionsPadding: 'pl-10',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label2: '3. What is your target profit margin?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'10%',
				'15%',
				'25%',
				'Other: [Specify]',
			],
			optionsPadding: 'pl-10',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'checkbox',
			label2: '4. What are your team development goals? (Check all that apply)',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Improve Leadership Skills',
				'Better Sales Training',
				'Increase Digital Marketing Skills',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label2: '5. How much would you like to reduce your involvement in day-to-day operations?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'A Lot (Delegate most tasks)',
				'Somewhat (Delegate some tasks)',
				'A Little (Remain highly involved)',
				'No Reduction Desired',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label2: '6. Do you want to automate your business processes?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Yes, most processes',
				'Yes, key processes',
				'No, I don’t need automation',
			],
			optionsPadding: 'pl-10',
		},
	],
	section5: [
		{
			type: 'radio',
			label: 'A. Direct Meetings',
			label2: '1. How often would you like in-person meetings?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Weekly',
				'Bi-weekly',
				'Monthly',
				'As Needed',
				'No Preference (Flexible)',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label2: '2. How many in-person meetings do you think we’ll need?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'1-3',
				'4-6',
				'7-10',
				'10+',
				'As Needed',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label: 'B. Online Meetings',
			label2: '1. How often would you like online meetings?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Weekly',
				'Bi-weekly',
				'Monthly',
				'As Needed',
				'No Preference (Flexible)',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label2: '2. Which online platform do you prefer for meetings?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Zoom',
				'Microsoft Teams',
				'Google Meet',
				'Other: [Specify]',
			],
			optionsPadding: 'pl-10',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label2: '3. How many online meetings do you think we’ll need?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'1-3',
				'4-6',
				'7-10',
				'10+',
				'As Needed',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'checkbox',
			label: 'C. Project Focus',
			label2: '1. Which stages of the project are most important to you? (Check all that apply)',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Stage 1: Strategy Planning and Documentation (Plan)',
				'Stage 2: Team Recruitment and Onboarding (Do)',
				'Stage 3: Training and Development (Do)',
				'Stage 4: Implementation and Performance Capturing (Check)',
				'Stage 5: Review and Adjustment (Adjust)',
				'Stage 6: Performance Acceleration (Adjust)',
			],
			optionsPadding: '30px',
		},
		{
			type: 'radio',
			label2: '2. Would you like to focus on all stages or just a few?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'All Stages',
				'Just a Few: [Specify which]',
			],
			optionsPadding: 'pl-10',
			additionalFieldOption: 'Just a Few: [Specify which]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'radio',
			label: 'D. Commitment Level',
			label2: '1. How committed are you to making changes and investing in growth?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Fully Committed (Ready to make changes)',
				'Mostly Committed (Will implement most suggestions)',
				'Somewhat Committed (Will consider suggestions)',
				'Not Sure (Need more information)',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label2: '2. How much involvement do you want from your leadership team?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'High Involvement (Daily/Weekly check-ins)',
				'Moderate Involvement (Bi-weekly/Monthly check-ins)',
				'Low Involvement (Occasional updates)',
				'Minimal Involvement (We’ll manage it)',
			],
			optionsPadding: 'pl-10',
		},
	],
	section6: [
		{
			type: 'checkbox',
			label: 'A. Key Gaps',
			label2: '1. What are the key gaps in your customer base compared to your goal?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Not Enough New Customers',
				'Low Customer Retention',
				'Poor Lead Generation',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'checkbox',
			label2: '2. What are the key gaps in your revenue compared to your goal?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Slow Sales Growth',
				'High Costs',
				'Low Profit Margins',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'checkbox',
			label2: '3. What are the key gaps in your team performance?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Lack of Training',
				'Poor Leadership',
				'Low Employee Engagement',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'checkbox',
			label: 'B. Immediate Priorities',
			label2: '1. What are the most important areas to fix right away?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Increase Sales Team Size',
				'Get a New CRM System',
				'Improve Marketing Strategy',
				'Enhance Leadership Development',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
		{
			type: 'checkbox',
			label: 'C. Long-Term Focus',
			label2: '1. What are your long-term business goals? (Check all that apply)',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Expand to New Markets',
				'Increase Market Share',
				'Develop New Products/Services',
				'Other: [Specify]',
			],
			optionsPadding: '30px',
			additionalFieldOption: 'Other: [Specify]',
			additionalFieldValue: '',
			additionalFieldMultiline: true,
			additionalFieldMaxrows: 5,
		},
	],
	section7: [
		{
			type: 'radio',
			label: 'A. Project Scope',
			label2: '1. How complex is your business?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Simple (One location, small team)',
				'Moderate (Several departments or locations)',
				'Complex (Advanced technology, large team)',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label2: '2. How large is your team?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Small (1-10 members)',
				'Medium (11-50 members)',
				'Large (51+ members)',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label: 'B. Preferred Timeline',
			label2: '1. How quickly do you want to achieve your goals?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'1-3 months',
				'4-6 months',
				'7-12 months',
				'More than 12 months',
			],
			optionsPadding: 'pl-10',
		},
		{
			type: 'radio',
			label: 'C. Budget Considerations',
			label2: '1. What is your budget for this project?',
			label2Padding: 'pl-5',
			values: '',
			readOnly: false,
			error: false,
			required: true,
			errorMessage: 'Please select atleast one option',
			options: [
				'Less than ₹1 Lakh',
				'₹1-3 Lakhs',
				'₹3-5 Lakhs',
				'More than ₹5 Lakhs',
			],
			optionsPadding: 'pl-10',
		},
	],
	section8: [
		{
			type: 'text',
			label: 'A. Main Goals Summary',
			placeholder: 'Insert a summary of the client’s main goals',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'B. Challenges Summary',
			placeholder: 'Insert a summary of the main challenges identified',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'C. Next Steps',
			label2: '1. Immediate Actions',
			label2Padding: 'pl-5',
			placeholder: 'List the immediate actions, e.g., sign agreement, start training programs',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
		{
			type: 'text',
			label: 'D. Client Acknowledgment',
			label2: '1. Approved By',
			label2Padding: 'pl-5',
			placeholder: 'Client’s Name and Signature',
			fieldPadding: '20px',
			value: '',
			readOnly: false,
			multiline: true,
			maxrows: 5,
			error: false,
			required: false,
			errorMessage: 'Please fill out this field',
		},
	]
}

export {Fields};